const API_BASE = String(window.RENDER_API_BASE || "https://seven445-social-api.onrender.com/api").replace(/\/$/, "");
const configured = API_BASE.startsWith("https://") && !API_BASE.includes("YOUR-RENDER-SERVICE");
const $ = id => document.getElementById(id);
let mode = "login", token = localStorage.getItem("7445_token") || "", session = null;
let profile = null, posts = [], demoMode = false, demoUser = null, stories = [];
const demoPosts = [
 {id:"demo1",user_id:"arjun",profiles:{display_name:"Arjun Roy",username:"arjun"},content:"Kolkata evenings just hit different ❤️",created_at:new Date().toISOString(),likes_count:24,liked:false,comments:[]},
 {id:"demo2",user_id:"riya",profiles:{display_name:"Riya Sen",username:"riya"},content:"New day, new vibe ✨ What made you smile today?",created_at:new Date(Date.now()-3600000).toISOString(),likes_count:41,liked:false,comments:[]}
];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function initials(name){return (name||"U").trim().split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase()}
function showStatus(id,msg,error=false){const el=$(id);if(!el)return;el.textContent=msg;el.classList.toggle("hidden",!msg);el.classList.toggle("error",!!error);el.classList.toggle("good",!!msg&&!error)}
function toastMsg(t){$("toast").textContent=t;$("toast").style.display="block";clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$("toast").style.display="none",2400)}
async function api(path, options={}) {
 if(!configured) throw new Error("Render backend is not configured yet. Please set the API URL in render-config.js.");
 const headers={"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{}),...(options.headers||{})};
 const res=await fetch(API_BASE+path,{...options,headers});
 if(res.status===204)return null;
 let body={};try{body=await res.json()}catch{}
 if(!res.ok)throw new Error(body.error||("Request failed ("+res.status+")"));
 return body;
}
function setMode(m){mode=m;$("loginTab").classList.toggle("active",m==="login");$("signupTab").classList.toggle("active",m==="signup");$("name").classList.toggle("hidden",m!=="signup");$("name").required=m==="signup";$("authSubmit").textContent=m==="signup"?"Create my account":"Log in";$("pass").autocomplete=m==="signup"?"new-password":"current-password";showStatus("authStatus","",false)}
$("authForm").addEventListener("submit",async e=>{
 e.preventDefault();const btn=$("authSubmit");btn.disabled=true;showStatus("authStatus","Connecting…");
 try{
  if(!configured)throw new Error("Render backend URL isn't configured yet. You can still explore demo mode.");
  const body={email:$("email").value.trim().toLowerCase(),password:$("pass").value};
  let data;
  if(mode==="signup"){body.display_name=$("name").value.trim();body.username=body.display_name.toLowerCase().replace(/[^a-z0-9_]/g,"").slice(0,24);data=await api("/auth/signup",{method:"POST",body:JSON.stringify(body)})}
  else data=await api("/auth/login",{method:"POST",body:JSON.stringify(body)});
  token=data.token;localStorage.setItem("7445_token",token);profile=data.user;session={user:data.user};demoMode=false;posts=await fetchPosts();startApp();
 }catch(err){showStatus("authStatus",err.message||"Couldn't connect. Please try again.",true)}finally{btn.disabled=false}
});
function demo(){demoMode=true;token="";session=null;stories=JSON.parse(localStorage.getItem("7445_demo_stories")||"null")||[{id:"s1",name:"Arjun",text:"Kolkata sunset 🌇"},{id:"s2",name:"Riya",text:"Good vibes only ✨"},{id:"s3",name:"Neha",text:"Hello, friends! 👋"},{id:"s4",name:"Sayan",text:"Have a great day ☀️"}];demoUser={id:"demo-user",display_name:"Harsha",username:"harsha",email:"demo@7445.social"};profile=demoUser;posts=JSON.parse(localStorage.getItem("7445_demo_posts")||"null")||demoPosts;startApp();toastMsg("Demo mode — changes stay on this device")}
async function fetchPosts(){if(demoMode)return posts;const d=await api("/posts");return d.posts||[]}
async function startOnline(){if(!configured||!token)return false;try{const d=await api("/me");profile=d.user;session={user:d.user};posts=await fetchPosts();startApp();return true}catch(e){token="";localStorage.removeItem("7445_token");return false}}
function startApp(){$("auth").classList.add("hidden");$("app").classList.remove("hidden");$("hello").textContent="Hey, "+(profile?.display_name||"there")+" 👋";render();const note=demoMode?"Demo mode · posts stay on this device":(!configured?"Preview mode · configure Render API to activate shared posts":"Connected to 7445 Social");$("feedStatus").textContent=note;$("feedStatus").classList.remove("hidden");$("setupNote").textContent=configured?"Backend configured. Sign up or log in to share with everyone.":"Real accounts aren't connected yet. Deploy the Render backend, then add its URL to render-config.js."}
function render(){renderStories();renderFeed();renderProfile();searchPeople()}
function renderStories(){const el=document.querySelector(".stories");if(!el)return;el.innerHTML='<button class="story" style="border:0;background:none;cursor:pointer" onclick="createStory()"><div class="avatar me">＋</div>Create</button>'+stories.map(s=>'<button class="story" style="border:0;background:none;cursor:pointer" onclick="viewStory(\''+esc(s.id)+\'\')"><div class="avatar">'+esc(initials(s.name))+'</div>'+esc(s.name)+'</button>').join("");}
function createStory(){if(!demoMode){toastMsg("Stories are currently available in demo mode.");return}const text=prompt("Write a short story (text only):");if(!text||!text.trim())return;stories.unshift({id:"story-"+Date.now(),name:profile.display_name,text:text.trim(),created_at:new Date().toISOString()});localStorage.setItem("7445_demo_stories",JSON.stringify(stories));renderStories();toastMsg("Your story was added 🎉")}
function viewStory(id){const s=stories.find(x=>String(x.id)===String(id));if(s)alert(s.name+"’s story\n\n"+s.text);}
function renderFeed(){if(!posts.length){$("feed").innerHTML='<div class="empty"><strong>Your feed starts here</strong>Share the first update with your community.</div>';return}
 $("feed").innerHTML=posts.map(p=>{const who=p.profiles?.display_name||"Community member",handle=p.profiles?.username||"member",comments=p.comments||[];return '<article class="post"><div class="phead"><div class="sm">'+esc(initials(who))+'</div><div class="pmeta"><b>'+esc(who)+'</b><div class="muted">@'+esc(handle)+' · '+esc(timeAgo(p.created_at))+'</div></div></div><div class="posttext">'+esc(p.content||"")+'</div>'+(p.image_url?'<img class="postimg" loading="lazy" src="'+esc(p.image_url)+'" alt="Post photo">':"")+'<div class="postactions"><button class="action '+(p.liked?"liked":"")+'" onclick="toggleLike(\''+esc(p.id)+'\')">'+(p.liked?"♥ Liked":"♡ Like")+'</button><button class="action" onclick="focusComment(\''+esc(p.id)+'\')">▢ '+(p.comments_count??comments.length)+' comments</button><button class="action" onclick="sharePost(\''+esc(p.id)+'\')">↗ Share</button></div><div class="likesline">♥ '+(p.likes_count||0)+' likes</div><div class="commentlist">'+comments.slice(-2).map(c=>'<div><b>'+esc(c.profiles?.display_name||"Member")+'</b> '+esc(c.content||"")+'</div>').join("")+'</div><form class="commentbox" onsubmit="addComment(event,\''+esc(p.id)+'\')"><input id="comment-'+esc(p.id)+'" maxlength="500" placeholder="Write a comment…" aria-label="Write a comment"><button>Send</button></form></article>'}).join("")}
function timeAgo(date){if(!date)return"just now";const mins=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/60000));if(!Number.isFinite(mins))return"recently";if(mins<1)return"just now";if(mins<60)return mins+"m ago";if(mins<1440)return Math.floor(mins/60)+"h ago";return Math.floor(mins/1440)+"d ago"}
async function toggleLike(id){const p=posts.find(x=>String(x.id)===String(id));if(!p)return;if(demoMode){p.liked=!p.liked;p.likes_count=(p.likes_count||0)+(p.liked?1:-1);localStorage.setItem("7445_demo_posts",JSON.stringify(posts));renderFeed();return}try{const d=await api("/posts/"+encodeURIComponent(id)+"/likes",{method:"POST",body:"{}"});p.liked=d.liked;p.likes_count=d.likes_count;renderFeed()}catch(e){toastMsg(e.message)}}
function focusComment(id){$("comment-"+id)?.focus()}
async function addComment(e,id){e.preventDefault();const input=$("comment-"+id),content=input.value.trim();if(!content)return;const p=posts.find(x=>String(x.id)===String(id));if(demoMode){p.comments=p.comments||[];p.comments.push({profiles:{display_name:profile.display_name},content});localStorage.setItem("7445_demo_posts",JSON.stringify(posts));input.value="";renderFeed();return}try{await api("/posts/"+encodeURIComponent(id)+"/comments",{method:"POST",body:JSON.stringify({content})});posts=await fetchPosts();renderFeed()}catch(err){toastMsg(err.message)}}
function sharePost(id){const url=location.href.split("#")[0]+"#post-"+encodeURIComponent(id);if(navigator.share)navigator.share({title:"7445 Social",text:"Check out this post on 7445 Social",url}).catch(()=>{});else if(navigator.clipboard)navigator.clipboard.writeText(url).then(()=>toastMsg("Post link copied")).catch(()=>toastMsg(url));else toastMsg(url)}
function preview(){const f=$("file").files[0];if(!f)return;if(f.size>5*1024*1024){toastMsg("Please choose a photo under 5 MB");$("file").value="";return}if(demoMode){const r=new FileReader();r.onload=()=>{$("previewImg").src=r.result;$("previewImg").classList.remove("hidden")};r.readAsDataURL(f)}else{toastMsg("For online posts, paste a public HTTPS photo link in the field below.");$("imageUrl").focus()}}
async function publish(){const content=$("caption").value.trim(),file=$("file").files[0],image_url=$("imageUrl").value.trim()||null;if(!content&&!file&&!image_url){showStatus("publishStatus","Write something or add a photo link.",true);return}if(image_url&&!/^https:\/\//i.test(image_url)){showStatus("publishStatus","Photo links must start with https://",true);return}if(file&&!demoMode&&!image_url){showStatus("publishStatus","Online photo uploads need a storage provider. Paste a public HTTPS photo link for now.",true);return}if(file&&file.size>5*1024*1024){showStatus("publishStatus","Please choose a photo under 5 MB.",true);return}
 const btn=$("publishBtn");btn.disabled=true;showStatus("publishStatus","Publishing…");try{let finalImage=image_url;if(demoMode&&file){finalImage=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
 if(demoMode){posts.unshift({id:"local-"+Date.now(),user_id:profile.id,profiles:{display_name:profile.display_name,username:profile.username},content,image_url:finalImage,created_at:new Date().toISOString(),likes_count:0,liked:false,comments:[]});localStorage.setItem("7445_demo_posts",JSON.stringify(posts))}
 else{await api("/posts",{method:"POST",body:JSON.stringify({content,image_url:finalImage})});posts=await fetchPosts()}
 $("caption").value="";$("file").value="";$("imageUrl").value="";$("previewImg").classList.add("hidden");showStatus("publishStatus","");render();go("home",document.querySelector(".nav"));toastMsg("Post shared 🎉")
 }catch(err){showStatus("publishStatus",err.message||"Couldn't publish post.",true)}finally{btn.disabled=false}}
function renderProfile(){const p=profile||demoUser||{display_name:"Guest",username:"guest"};$("big").textContent=initials(p.display_name);$("pname").textContent=p.display_name||"Guest";$("handle").textContent="@"+(p.username||"guest");const mine=posts.filter(x=>String(x.user_id)===String(p.id));$("count").textContent=mine.length;$("followers").textContent=p.followers_count||0;$("following").textContent=p.following_count||0;$("mine").innerHTML=mine.length?mine.map(x=>'<div class="card">'+esc(x.content||"")+(x.image_url?'<img class="postimg" style="margin-top:10px" src="'+esc(x.image_url)+'">':"")+'</div>').join(""):'<div class="empty">Your shared posts will appear here.</div>'}
async function editProfile(){if(demoMode){const n=prompt("Display name",profile.display_name);if(n&&n.trim()){profile.display_name=n.trim();startApp()}return}if(!token)return toastMsg("Log in to edit your profile");const n=prompt("Display name",profile.display_name);if(n&&n.trim())try{const d=await api("/me",{method:"PATCH",body:JSON.stringify({display_name:n.trim()})});profile=d.user;startApp()}catch(e){toastMsg(e.message)}}
let searchTimer=null;
async function searchPeople(){const q=($("search")?.value||"").trim().toLowerCase();if(!configured||demoMode){const people=[{id:"arjun",display_name:"Arjun Roy",username:"arjun"},{id:"riya",display_name:"Riya Sen",username:"riya"},{id:"neha",display_name:"Neha Mitra",username:"neha"},{id:"sayan",display_name:"Sayan Das",username:"sayan"}].filter(x=>(x.display_name+" "+x.username).toLowerCase().includes(q));$("results").innerHTML=people.map(p=>'<div class="searchres"><div class="sm">'+esc(initials(p.display_name))+'</div><div class="pmeta"><b>'+esc(p.display_name)+'</b><div class="muted">@'+esc(p.username)+'</div></div><span class="muted">Preview</span></div>').join("");return}
 if(q.length<2){$("results").innerHTML="";return}clearTimeout(searchTimer);searchTimer=setTimeout(async()=>{try{const d=await api("/profiles?q="+encodeURIComponent(q));const people=(d.profiles||[]).filter(p=>String(p.id)!==String(profile?.id));$("results").innerHTML=people.map(p=>'<div class="searchres"><div class="sm">'+esc(initials(p.display_name))+'</div><div class="pmeta"><b>'+esc(p.display_name)+'</b><div class="muted">@'+esc(p.username)+'</div></div><button class="smallbtn" onclick="toggleFollow(\''+esc(p.id)+'\',this)">Follow</button></div>').join("")||'<div class="muted">No members found yet.</div>'}catch(e){$("results").innerHTML='<div class="muted">Could not search right now.</div>'}},250)}
async function toggleFollow(id,btn){if(demoMode){btn.textContent=btn.textContent==="Follow"?"Following":"Follow";return}try{const d=await api("/profiles/"+encodeURIComponent(id)+"/follow",{method:"POST",body:"{}"});btn.textContent=d.following?"Following":"Follow"}catch(e){toastMsg(e.message)}}
function go(id,el){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));el?.classList.add("active");if(id==="explore")$("search").focus({preventScroll:true})}
async function logout(){if(token)localStorage.removeItem("7445_token");token="";session=null;profile=null;posts=[];demoMode=false;$("app").classList.add("hidden");$("auth").classList.remove("hidden");$("pass").value="";showStatus("authStatus","");setMode("login")}
async function init(){if(!configured){$("setupNote").textContent="Real accounts aren't connected yet. Deploy the Render backend and add its HTTPS URL to render-config.js. Demo mode is available now.";return}await startOnline()}
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
init();
